FROM arm32v6/node:8.14.0-alpine
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

ADD package.json /app/package.json
ADD package-lock.json /app/package-lock.json
ADD node_modules /app/node_modules
ADD app.js /app
ADD db.js /app
ADD support/gammu.sql /app/gammu.sql
ADD client/build /app/client/build

ENV PORT=5000
ENV NODE_ENV=production
ENV SERVE_STATIC=1
EXPOSE 5000
CMD [ "npm", "start" ]
