version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgres://smsd:smsd@db:5432/smsd
      NODE_ENV: production
      SERVE_STATIC: 1
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10.2-alpine
    ports:
      - "5433:5432"
    environment:
      TZ: Europe/Stockholm
      POSTGRES_DB: smsd
      POSTGRES_USER: smsd
      POSTGRES_PASSWORD: smsd
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
